### ISSUE TITLE
[SEQ-1710] Export FCP XML + Asset Bundle [Converted to "Export FCP XML + Asset Bundle" project]

### ISSUE THREAD

**Issue by lmcgartland** [sequencefilm/docs-and-issues#3]
<sub>From [SyncLinear.com](https://synclinear.com) | [SEQ-1710](https://linear.app/sequencefilm/issue/SEQ-1710/export-fcp-xml-asset-bundle-[converted-to-export-fcp-xml-asset-bundle)</sub>

**Comment by latenitefilms** [comment]
This would be SUPER cool.

**Comment by lmcgartland** [comment]
Good first task for future CTO!

**Comment by lmcgartland** [comment]
@bwilliams is this something you think you can knock this out quickly? Parker thinks it's still pretty important for interop

**Comment by lmcgartland** [comment]
There should be a way to do GES to FCP 7 XML using OTIO, but I don't think Erik could figure it out.

**Comment by lmcgartland** [comment]
We could try that built in converter before doing our own.
