### ISSUE TITLE
[SEQ-1977] Support MXF container format

### ISSUE THREAD

**Issue by lmcgartland** [sequencefilm/docs-and-issues#56]
<sub>From [SyncLinear.com](https://synclinear.com) | [SEQ-1977](https://linear.app/sequencefilm/issue/SEQ-1977/support-mxf-container-format)</sub>

**Comment by lmcgartland** [comment]
In progress. @abrowne2 created an initial patch today to enable support.

**Comment by abrowne2** [comment]
Have an initial MXF patch in. It's needs some refinement but working in timeline / library.


https://github.com/sequencefilm/docs-and-issues/assets/17056114/a602b482-7b22-4b52-a430-2aca12f4fc84
